### ISSUE TITLE
The application crashes  trying to use it with Oracle JDK

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/embedded-samples#17]
**Describe the bug**
Trying to run the application on Oracle JDK 11 crashes it.

**To Reproduce**
0.Install Oracle JDK11,maven,vscode, and Totalcross plugin for vscode
1. Go to the main class
2. Click on run
3. The application should crash, and show the exception at the console

**Expected behavior**
The simulator should run without major problems

**Screenshots**
dashboard-ew2020

![Issue](https://user-images.githubusercontent.com/29692098/94182365-43c88700-fe77-11ea-9b03-bfe4561c06fc.PNG)
HomeApplianceXML

![Issu2](https://user-images.githubusercontent.com/29692098/94182373-462ae100-fe77-11ea-820f-b9fcb4235eb0.PNG)

**Desktop (please complete the following information):**
 - OS:Windows 10 Pro(Virtual Machine)

**Comment by nmarquesin** [comment]
Issue related to [#153](https://github.com/TotalCross/totalcross/issues/153)

**Comment by acmlira** [comment]
Duplicated in [issue #153](https://github.com/TotalCross/totalcross/issues/153)
