### ISSUE TITLE
Printer sample crashing on RaspberryPi

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/embedded-samples#2]
**Describe the bug**
Printer sample is crashing when some button is clicked

**To Reproduce**
Run printer sample on raspberry pi, and click some button

**Expected behavior**
The button should take you to a new screen

**Screenshots**

![image](https://user-images.githubusercontent.com/29692098/100378859-add5e780-2ff2-11eb-8c89-15bd3b2a80f5.png)
![image](https://user-images.githubusercontent.com/29692098/100379025-f8effa80-2ff2-11eb-8fbd-d3f971a1546a.png)

**Desktop (please complete the following information):**
-Device:Raspberry pi 3 model B+
-Os:raspbian

**Comment by brunoamuniz** [comment]
@Iaggoq @pattrickx do you know what is happening?

**Comment by Iaggoq** [comment]
Its seems to be some problem with a java class @VicMisael which button is causing the error?

**Comment by VicMisael** [comment]
@Iaggoq Any button you click causes the issue

**Comment by Iaggoq** [comment]
@VicMisael interesting, on monday i will send a sample with some instructions to you, if somehow i forgot to do that i ask you remind me

**Comment by Iaggoq** [comment]
fixed in #7
