### ISSUE TITLE
Toradex Launcher crashing in raspberry pi

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/embedded-samples#4]
**Describe the bug**
When some option is clicked, the application crashes

**To Reproduce**
Open the application compiled for linux arm,and click some button
**Expected behavior**
A menu should open

**Screenshots**
the same issue as related in #2 
![image](https://user-images.githubusercontent.com/29692098/100379706-170a2a80-2ff4-11eb-80c4-ea8fb7fb2851.png)

**Device**
 - Device: Raspberry pi 3 b+
 - OS: Raspbian

**Additional context**
Related #2

**Comment by VicMisael** [comment]
Any button clicked also crashes the application

**Comment by Iaggoq** [comment]
fixed in #7
